server:
  forward-headers-strategy: framework
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 123
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#  api-docs.path: /api-docs
